# Generated by Django 3.2.5 on 2021-07-21 04:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_ratings_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='stars',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterIndexTogether(
            name='ratings',
            index_together={('user', 'movie')},
        ),
    ]
